### ISSUE TITLE
When picking transparant color (with zenity) pickachu crashes

### ISSUE THREAD

**Issue by bitsofreedom** [DougBeney/pickachu#2]
![image](https://user-images.githubusercontent.com/34915492/34918938-ec7d7f5a-f95b-11e7-8e69-574668ee3129.png)

![image](https://user-images.githubusercontent.com/34915492/34918949-fd81509c-f95b-11e7-9dce-314e82457b65.png)

```
Error detected while processing function Pickachu:
line    4:
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/home/bart/dotfiles/vim/.vim/bundle/pickachu/plugin/pickachu.py", line 121, in MainFuncti
on
    output = runApp(CHOOSEN_APP, CHOOSEN_FORMAT)
  File "/home/bart/dotfiles/vim/.vim/bundle/pickachu/plugin/pickachu.py", line 99, in runApp
    return app['processor'](output.rstrip())
  File "/home/bart/dotfiles/vim/.vim/bundle/pickachu/plugin/pickachu.py", line 29, in colorProces
sor
    hex = '#%02x%02x%02x' % (int(array[0]), int(array[1]), int(array[2]))
ValueError: invalid literal for int() with base 10: 'a(37'
```

**Comment by DougBeney** [comment]
Thanks for using Pickachu! I just fixed this issue in the last commit. :)
Update the plugin and you should be good to go.
