### ISSUE TITLE
qarma and rgba error

### ISSUE THREAD

**Issue by tofulm** [DougBeney/pickachu#6]
hi,
I've an error with qarma et rgba

```
Erreur détectée en traitant function Pickachu[4]..provider#python3#Call :                                                                    
ligne   18 :                                                                                                                                 
Traceback (most recent call last):                                                                                                           
  File "<string>", line 2, in <module>                                                                                                       
  File "/home/tof/.vim/bundle/pickachu/plugin/pickachu/main.py", line 26, in MainFunction                                                    
    output = apps.runApp(CHOOSEN_APP, CHOOSEN_FORMAT)                                                                                        
  File "/home/tof/.vim/bundle/pickachu/plugin/pickachu/apps.py", line 58, in runApp                                                          
    return app['processor'](output.rstrip())                                                                                                 
  File "/home/tof/.vim/bundle/pickachu/plugin/pickachu/processors.py", line 72, in colorProcessor                                            
    if i < len(array) - 1:                                                                                                                   
UnboundLocalError: local variable 'array' referenced before assignment  
```

thanks

**Comment by DougBeney** [comment]
Hi, @tofulm! Thanks for taking time to make this report. I just pushed a fix. 
Please update Pickachu via your Vim plugin manager and you should be good to go!
Let me know if any other problems arise.

**Comment by tofulm** [comment]
Thanks, it's good !
